#服务配置
server:
  port: 8005

# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_wx?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    username: root
    password: root

# 微信
wx:
  app-id: xxxxxxxxxxx
  app-secret: xxxxxxxxxxxxx
  msgDataFormat: JSON
